# Common base configuration (build + shared settings)
x-base: &base               # ← note the x- prefix
  image: pmcochrane/bitaxe-stabiliser:${TAG:-latest}
  build:
    context: .
  volumes:
    - ./deviceData:/app/deviceData
  # environment: 
      # - BITAXE_HOSTNAME=${BITAXE_HOSTNAME:-}
      # - PORT=${PORT:-3000}
      # - HISTORY_LIMIT=${HISTORY_LIMIT:-172800}
      # - TARGET_ASIC=${TARGET_ASIC:-65}
      # - MAX_VR=${MAX_VR:-80}
      # - CORE_VOLTAGE=${CORE_VOLTAGE:-1150}
      # - MAX_FREQ=${MAX_FREQ:-525.0}
      # - STEP_DOWN_DEFAULT=${STEP_DOWN_DEFAULT:- -10}
  restart: unless-stopped
  logging:                  # ← add this block
    driver: "json-file"     # usually optional (it's the default), but good to be explicit
    options:
      max-size: "10m"       # each individual log file max 10 MB (before rotation)
      max-file: "5"         # keep 5 files total → oldest gets deleted automatically
                             # → total log disk usage per container ≈ 50 MB max
  

services:
  # Config for bitaxe device 1
  # bitaxe-stabiliser-g1:
  #   <<: *base
  #   environment:
  #     - BITAXE_IP=${BITAXE_IP_1}
  #   ports:
  #     - "${PORT_1:-3001}:3000"

  # Config for bitaxe device 2
  bitaxe-stabiliser-g2:
    <<: *base
    environment:
      - BITAXE_IP=${BITAXE_IP_2}
    ports:
      - "${PORT_2:-3002}:3000"
